version: '2'

services:
  web:
    build: .
    image: gadgetopia
    platform: linux/amd64
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: gadgetopia
    volumes:
      - .:/gadgetopia
    ports:
      - "8000:8000"
    env_file:
      - .env